// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAToJumHCxeX0C_GbOesyM3CLWW6IjycVY',
    appId: '1:609991724580:web:2b616d5d77625d31fb52b1',
    messagingSenderId: '609991724580',
    projectId: 'linatyapp',
    authDomain: 'linatyapp.firebaseapp.com',
    storageBucket: 'linatyapp.firebasestorage.app',
    measurementId: 'G-GMJ2MTKEBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9tikhWsYxMMsKIyLXDK3dwva6tunaIM',
    appId: '1:609991724580:android:4379c1881d1addfefb52b1',
    messagingSenderId: '609991724580',
    projectId: 'linatyapp',
    storageBucket: 'linatyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsVMnVWhhHOs9r9XOD5Gs20WWe3LUpbmc',
    appId: '1:609991724580:ios:b018996c9e992804fb52b1',
    messagingSenderId: '609991724580',
    projectId: 'linatyapp',
    storageBucket: 'linatyapp.firebasestorage.app',
    iosBundleId: 'com.example.linaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsVMnVWhhHOs9r9XOD5Gs20WWe3LUpbmc',
    appId: '1:609991724580:ios:b018996c9e992804fb52b1',
    messagingSenderId: '609991724580',
    projectId: 'linatyapp',
    storageBucket: 'linatyapp.firebasestorage.app',
    iosBundleId: 'com.example.linaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAToJumHCxeX0C_GbOesyM3CLWW6IjycVY',
    appId: '1:609991724580:web:b37f4ff90fc8160afb52b1',
    messagingSenderId: '609991724580',
    projectId: 'linatyapp',
    authDomain: 'linatyapp.firebaseapp.com',
    storageBucket: 'linatyapp.firebasestorage.app',
    measurementId: 'G-ZVS68LYNVL',
  );
}
